#pragma once
#include "HookDemo/HookDemo.hpp"
#include "DemoSystem.hpp"
#include "DemoJSONReader/DemoJSONReader.hpp"
#include "DemoHelper/DemoHelper.hpp"
#include "DemoAnalyzer/DemoAnalyzer.hpp"
#include "DemoRecorder/DemoRecorder.hpp"
#include "RecordTaskMaker/RecordTaskMaker.hpp"
#include "RecordTaskConfiger/RecordTaskConfiger.hpp"