path: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe
launchOptions: -insecure -novid -allow_third_party_software -worldwide
patternsCheckDangerous:
  - 完美世界竞技