name: "MulNX 官方快捷键配置"

# vkCode 是Windows平台的虚拟键码，请查阅相关文档，以十进制的形式修改！

buttons:
  - name: "place camera" # 放置关键帧
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: false
      vkCode: 20 # 大写锁定键
      comboClick: 1

  - name: "CamMovUp" # 摄像机上升，默认R
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: false
      vkCode: 82
      comboClick: 1

  - name: "CamMovDown" # 摄像机下降，默认F
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: false
      vkCode: 70
      comboClick: 1

binds:
  - desc: "触发全局保存（alt+S）"
    msg: "Global/Save"
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: true
      vkCode: 83
      comboClick: 1

  - desc: "停止运镜（alt+P）"
    msg: "CameraSystem/Play/Shutdown"
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: true
      vkCode: 80
      comboClick: 1

  - desc: "切换自由摄像机模式（Alt+T）"
    msg: "FreeCamCtrl/Toggle"
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: true
      vkCode: 84
      comboClick: 1
    
  - desc: "切换UI显示（Insert）"
    msg: "UISystem/Toggle"
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: false
      vkCode: 45
      comboClick: 1

  - desc: "开启自瞄"
    msg: "AutoAim/Enable"
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: true
      vkCode: 86
      comboClick: 1

  - desc: "关闭自瞄"
    msg: "AutoAim/Disable"
    KCP:
      usable: true
      ctrl: false
      shift: false
      alt: true
      vkCode: 86
      comboClick: 2